### ISSUE TITLE
About error 

### ISSUE THREAD

**Issue by xiaolijz** [xlang-ai/text2reward#3]
Hello, I am meeting a problem about executing the code, `Some required Vulkan extension is not present. You may not use the renderer to render, however, CPU resources will be still available.`, I am so glad you can provide a solution for me, but the Web Link is invalid. If you still have this document, could you send me a link? Thank you very much!

**Comment by sihengz02** [comment]
Hi, it seems that ManiSkill2 team updated their website, so the old link is not available. I just found the new link is here https://maniskill.readthedocs.io/en/latest/user_guide/getting_started/installation.html#vulkan

**Comment by xiaolijz** [comment]
> Hi, it seems that ManiSkill2 team updated their website, so the old link is not available. I just found the new link is here https://maniskill.readthedocs.io/en/latest/user_guide/getting_started/installation.html#vulkan
Thank you for your reply. I solved this error simply by reinstalling Nvidia Force.

**Comment by Ziyu0118** [comment]
Hi, how long does it take in your platform to get the response from LLM?
